# SPDX-FileCopyrightText: : 2017-2020 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: CC0-1.0

version: 0.4.0
tutorial: false

logging:
  level: INFO
  format: "%(levelname)s:%(name)s:%(message)s"

summary_dir: results

scenario:
  simpl: [""]
  ll: [v2.25]
  clusters: [27]
  opts: [Co2L-1H-CCL-onwind+p0.25]

countries: ["NL", "DE", "BE", "FR", "DK", "NO", "GB", "LU"]
# focus_weights:
#   'NL' : 0.2222
#   'DE' : 0.1852
#   'BE' : 0.0741
#   'FR' : 0.1852
#   'DK' : 0.0741
#   'NO' : 0.037
#   'GB' : 0.1852
#   'LU' : 0.037

enable:
  prepare_links_p_nom: false
  retrieve_databundle: true
  build_cutout: false
  retrieve_cutout: false
  copy_cutout: true
  build_natura_raster: false
  retrieve_natura_raster: true
  custom_busmap: true
  # will look for:
  # data/custom_busmap_elec_s{simpl}_{clusters}.csv
  override_stub_map: true #! custom WB
  # will look for:
  # data/overwrite_stubmap.csv
  legacy_gt_to_hydrogen: ["CCGT", "OCGT", "CCGT-nextgen", "OCGT-nextgen"] #! custom WB
  # will connect all listed carriers to the hydrogen buses and infer zero fuel cost and emmisions for these technologies
  extendable_carriers_to_all_nodes: true #! custom WB
  # used to allow all next-gen technologies to be placed at every node
  hydrogen_contant_loads_at_nodes: "data/hydrogen_demand_per_bus.csv" #! custom WB
  # used to apply a custom hydrogen load at every node based on synthesis data from Agora and IRENA

custom_loads: #! custom WB
  national_curve_overwrite_file: "data/custom_national_loads.csv"
  busbar_insert_curves_file: "data/custom_bus_loads.csv"

clustering:
  simplify:
    to_substations: false # network is simplified to nodes with positive or negative power injection (i.e. substations or offwind connections)

snapshots:
  start: "2015-01-01"
  end: "2016-01-01"
  closed: "left" # end is not inclusive

electricity:
  voltages: [220., 300., 380.]
  co2limit: -136795980.0
  co2base: 683979900.0
  agg_p_nom_limits: data/agg_p_nom_minmax.csv

  extendable_carriers:
    Generator: [
        "OCGT-nextgen",
        "CCGT-nextgen",
        "nuclear_nextgen",
        "BECCS",
        "DAC",
      ] # OCGT, CCGT
    StorageUnit: [battery] # battery, H2
    Store: [H2]
    Link: ["H2 pipeline"]

  max_hours:
    battery: 6
    H2: 168

  powerplants_filter: "Country not in ['BE', 'FR', 'DE', 'GB', 'NL'] and (Fueltype == 'Hydro' and Name != 'Psw Vianden') and (DateOut > 2050)"
  custom_powerplants: YearDecommissioning > 2050
  conventional_carriers: [nuclear, OCGT, CCGT, biomass, waste]
  renewable_capacities_from_OPSD: []

atlite:
  nprocesses: 4
  cutouts:
    europe-2015-era5:
      module: era5 # in priority order
      x: [-8., 32.]
      y: [41., 72.]
      time: ["2015", "2015"]

renewable:
  onwind:
    cutout: europe-2015-era5
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_2020ATB_5.5MW
    capacity_per_sqkm: 3 # ScholzPhd Tab 4.3.1: 10MW/km^2
    # correction_factor: 0.93
    corine:
      # Scholz, Y. (2012). Renewable energy based electricity supply at low costs:
      #  development of the REMix model and application for Europe. ( p.42 / p.28)
      grid_codes:
        [
          12,
          13,
          14,
          15,
          16,
          17,
          18,
          19,
          20,
          21,
          22,
          23,
          24,
          25,
          26,
          27,
          28,
          29,
          31,
          32,
        ]
      distance: 1000
      distance_grid_codes: [1, 2, 3, 4, 5, 6]
    natura: true
    potential: simple # or conservative
    clip_p_max_pu: 1.e-2
  offwind-ac:
    cutout: europe-2015-era5
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_2020ATB_15MW_offshore
    capacity_per_sqkm: 2
    correction_factor: 0.8855
    # proxy for wake losses
    # from 10.1016/j.energy.2018.08.153
    # until done more rigorously in #153
    corine: [44, 255]
    natura: true
    max_depth: 50
    max_shore_distance: 30000
    potential: simple # or conservative
    clip_p_max_pu: 1.e-2
  offwind-dc:
    cutout: europe-2015-era5
    resource:
      method: wind
      turbine: NREL_ReferenceTurbine_2020ATB_15MW_offshore
    # ScholzPhd Tab 4.3.1: 10MW/km^2
    capacity_per_sqkm: 2.4 # custom WB --> p+1.2 (2x1.2)
    correction_factor: 0.8855
    # proxy for wake losses
    # from 10.1016/j.energy.2018.08.153
    # until done more rigorously in #153
    corine: [44, 255]
    natura: true
    max_depth: 50
    min_shore_distance: 30000
    potential: simple # or conservative
    clip_p_max_pu: 1.e-2
  solar:
    cutout: europe-2015-era5
    resource:
      method: pv
      panel: CSi
      orientation:
        slope: 35.
        azimuth: 180.
    capacity_per_sqkm: 5.1 # custom WB --> p+3.0 (3x1.7) # ScholzPhd Tab 4.3.1: 170 MW/km^2
    # Correction factor determined by comparing uncorrected area-weighted full-load hours to those
    # published in Supplementary Data to
    # Pietzcker, Robert Carl, et al. "Using the sun to decarbonize the power
    # sector: The economic potential of photovoltaics and concentrating solar
    # power." Applied Energy 135 (2014): 704-720.
    # This correction factor of 0.854337 may be in order if using reanalysis data.
    # for discussion refer to https://github.com/PyPSA/pypsa-eur/pull/304
    # correction_factor: 0.854337
    corine:
      [
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        9,
        10,
        11,
        12,
        13,
        14,
        15,
        16,
        17,
        18,
        19,
        20,
        26,
        31,
        32,
      ]
    natura: true
    potential: simple # or conservative
    clip_p_max_pu: 1.e-2
  hydro:
    cutout: europe-2015-era5
    carriers: [ror, PHS, hydro]
    PHS_max_hours: 6
    hydro_max_hours: "energy_capacity_totals_by_country" # one of energy_capacity_totals_by_country, estimate_by_large_installations or a float
    clip_min_inflow: 1.0

lines:
  types:
    220.: "Al/St 240/40 2-bundle 220.0"
    300.: "Al/St 240/40 3-bundle 300.0"
    380.: "Al/St 240/40 4-bundle 380.0"
  s_max_pu: 0.7
  s_nom_max: .inf
  length_factor: 1.25
  under_construction: "zero" # 'zero': set capacity to zero, 'remove': remove, 'keep': with full capacity

links:
  p_max_pu: 1.0
  p_nom_max: .inf
  include_tyndp: true
  under_construction: "zero" # 'zero': set capacity to zero, 'remove': remove, 'keep': with full capacity

transformers:
  x: 0.1
  s_nom: 2000.
  type: ""

load:
  power_statistics: True # only for files from <2019; set false in order to get ENTSOE transparency data
  interpolate_limit: 3 # data gaps up until this size are interpolated linearly
  time_shift_for_large_gaps: 1w # data gaps up until this size are copied by copying from
  manual_adjustments: true # false
  scaling_factor: 1.4

costs:
  year: 2050
  discountrate: 0.0225 # From a Lion Hirth paper, also reflects average of Noothout et al 2016
  USD2013_to_EUR2013: 0.7532 # [EUR/USD] ECB: https://www.ecb.europa.eu/stats/exchange/eurofxref/html/eurofxref-graph-usd.en.html
  emission_prices: # in currency per tonne emission, only used with the option Ep
    co2: 0.

solving:
  options:
    formulation: kirchhoff
    load_shedding: false
    noisy_costs: true
    min_iterations: 1
    max_iterations: 2
    clip_p_max_pu: 0.01
    skip_iterations: true
    track_iterations: false
    #nhours: 10
  solver:
    name: gurobi
    threads: 6
    method: 2 # barrier
    crossover: 0
    BarConvTol: 1.e-4 # reduced 1 magnitude
    FeasibilityTol: 1.e-5 # reduced 1 magnitude
    AggFill: 0
    PreDual: 0
    GURO_PAR_BARDENSETHRESH: 200
  # solver:
  #   name: cplex
  #   threads: 4
  #   lpmethod: 4 # barrier
  #   solutiontype: 2 # non basic solution, ie no crossover
  #   barrier.convergetol: 1.e-5
  #   feasopt.tolerance: 1.e-6

plotting:
  map:
    figsize: [7, 7]
    boundaries: [-10, 15, 41, 60]
    p_nom:
      bus_size_factor: 5.e+4
      linewidth_factor: 3.e+3

  costs_max: 200
  costs_threshold: 1

  energy_max: 15000.
  energy_min: -10000.
  energy_threshold: 50.

  vre_techs: ["onwind", "offwind-ac", "offwind-dc", "solar", "ror"]
  conv_techs: ["OCGT", "CCGT", "Nuclear", "Coal"]
  storage_techs: ["hydro+PHS", "battery", "H2"]
  load_carriers: ["AC load"]
  AC_carriers: ["AC line", "AC transformer"]
  link_carriers: ["DC line", "Converter AC-DC"]
  tech_colors:
    "onwind": "#235ebc"
    "onshore wind": "#235ebc"
    "offwind": "#6895dd"
    "offwind-ac": "#6895dd"
    "offshore wind": "#6895dd"
    "offshore wind ac": "#6895dd"
    "offwind-dc": "#74c6f2"
    "offshore wind dc": "#74c6f2"
    "hydro": "#08ad97"
    "hydro+PHS": "#08ad97"
    "PHS": "#08ad97"
    "hydro reservoir": "#08ad97"
    "hydroelectricity": "#08ad97"
    "ror": "#4adbc8"
    "run of river": "#4adbc8"
    "solar": "#f9d002"
    "solar PV": "#f9d002"
    "solar thermal": "#ffef60"
    "biomass": "#0c6013"
    "solid biomass": "#06540d"
    "biogas": "#23932d"
    "waste": "#68896b"
    "geothermal": "#ba91b1"
    "gas": "#d35050"
    "natural gas": "#d35050"
    "coal": "#707070"
    "lignite": "#9e5a01"
    "oil": "#262626"
    "H2": "#ea048a"
    "hydrogen storage": "#ea048a"
    "battery": "#b8ea04"
    "Electric load": "#f9d002"
    "electricity": "#f9d002"
    "lines": "#70af1d"
    "transmission lines": "#70af1d"
    "AC-AC": "#70af1d"
    "AC line": "#70af1d"
    "links": "#8a1caf"
    "HVDC links": "#8a1caf"
    "DC-DC": "#8a1caf"
    "DC link": "#8a1caf"
    "nuclear_nextgen": "#ff9000"
    "OCGT-nextgen": "#d35050"
    "CCGT-nextgen": "#b20101"
    "nuclear": "#ffbc66"
    "OCGT": "#e59696"
    "CCGT": "#fe3a3a"
    "BECCS": "#425744"
    "DAC": "#85a388"

  nice_names:
    offwind-ac: "Offshore Wind (AC)"
    offwind-dc: "Offshore Wind (DC)"
    onwind: "Onshore Wind"
    solar: "Solar"
    PHS: "Pumped Hydro Storage"
    hydro: "Reservoir & Dam"
    battery: "Battery Storage"
    H2: "Hydrogen Storage"
    lines: "Transmission Lines"
    ror: "Run of River"
    OCGT: "Open-Cycle Gas Turbine (legacy)"
    CCGT: "Combined-Cycle Gas Turbine (legacy)"
    nuclear: "Nuclear (legacy)"
    OCGT-nextgen: "Open-Cycle Gas Turbine"
    CCGT-nextgen: "Combined-Cycle Gas Turbine"
    nuclear_nextgen: "Nuclear"
    BECCS: "Biomass CCS"
    DAC: "Direct air capture"
