map:
  figsize: [7, 7]
  boundaries: [-10, 15, 41, 60]
  p_nom:
    bus_size_factor: 5.e+4
    linewidth_factor: 3.e+3

costs_max: 200
costs_threshold: 1

energy_max: 15000.
energy_min: -10000.
energy_threshold: 50.

vre_techs: ["onwind", "offwind-ac", "offwind-dc", "solar", "ror"]
conv_techs: ["OCGT", "CCGT", "Nuclear", "Coal"]
storage_techs: ["hydro+PHS", "battery", "H2"]
load_carriers: ["AC load"]
AC_carriers: ["AC line", "AC transformer"]
link_carriers: ["DC line", "Converter AC-DC"]

nice_names:
  offwind-ac: "Wind op zee [AC]"
  offwind-dc: "Wind op zee [DC]"
  onwind: "Wind op land"
  solar: "Zon-PV"
  PHS: "Gepompte wateropslag"
  hydro: "Reservoir & Dam"
  battery: "Batterijopslag"
  H2: "Waterstofopslag"
  lines: "Transmissie kabels"
  ror: "Riviercentrale"
  OCGT: "Waterstofcentrale OCGT"
  CCGT: "Waterstofcentrale CCGT"
  nuclear: "Kernenergie"
  OCGT-nextgen: "Waterstofcentrale OCGT"
  CCGT-nextgen: "Waterstofcentrale CCGT"
  nuclear_nextgen: "Kernenergie nextgen"
  BECCS: "Biomassa+CCS"
  biomass: "Biomassa"
  DAC: "Direct air capture"
  waste: "Afvalverbranding"
  coal: "Kolen"
  H2 electrolysis: "Elektrolyse"
  offwind: "Wind op zee"
  H2 Fuel Cell: "H2-brandstofcel"
  hydro_combined: "Waterkracht" #non-pyPSA entry
  H2_combined: "Waterstofcentrale" #non-pyPSA entry

tech_colors:
  onwind: "#92d050"
  onshore wind: "#92d050"
  offwind: "#00b050"
  offwind-ac: "#00b050"
  offshore wind: "#00b050"
  offshore wind ac: "#00b050"
  offwind-dc: "#00b050"
  offshore wind dc: "#00b050"
  hydro: "#00b0f6"
  hydro+PHS: "#00b0f6"
  PHS: "#00b0f6"
  hydro reservoir: "#00b0f6"
  hydroelectricity: "#00b0f6"
  ror: "#00b0f6"
  run of river: "#00b0f6"
  solar: "#ffc400"
  solar PV: "#ffc400"
  solar thermal: "#ffc400"
  biomass: "#7f6000"
  solid biomass: "#7f6000"
  biogas: "#23932d"
  waste: "#7f6000"
  geothermal: "#ba91b1"
  gas: "#3b3838"
  natural gas: "#3b3838"
  coal: "#707070"
  lignite: "#9e5a01"
  oil: "#262626"
  H2: "#0070c0"
  H2 electrolysis: "#a64d79" #  [0, 112, 192] made purple to be distinct from H2 OCGT/CCGT
  hydrogen storage: "#0070c0"
  battery: "#b8ea04"
  Electric load: "#f9d002"
  electricity: "#f9d002"
  lines: "#70af1d"
  transmission lines: "#70af1d"
  AC-AC: "#70af1d"
  AC line: "#70af1d"
  links: "#8a1caf"
  HVDC links: "#8a1caf"
  DC-DC: "#8a1caf"
  DC link: "#8a1caf"
  nuclear_nextgen: "#ffff00"
  OCGT-nextgen: "#0070c0"
  CCGT-nextgen: "#0070c0"
  nuclear: "#ffff00"
  OCGT: "#0070c0"
  CCGT: "#0070c0"
  BECCS: "#425744"
  DAC: "#85a388"
  H2 Fuel Cell: "#0070c0"
  hydro_combined: "#00b0f6" #non-pyPSA entry
  H2_combined: "#0070c0" #non-pyPSA entry

region_nice_names:
  BE1 0: "BE O"
  BE1 1: "BE W"
  DE1 0: "DE W"
  DE1 1: "DE ZO"
  DE1 2: "DE NO"
  DE1 3: "DE ZW"
  DE1 4: "DE NW"
  DK1 0: "DK W"
  DK3 0: "DK O"
  FR1 0: "FR ZW"
  FR1 1: "FR NW"
  FR1 2: "FR N"
  FR1 3: "FR NO"
  FR1 4: "FR ZO"
  GB0 0: "VK ZO"
  GB0 1: "VK N"
  GB0 2: "VK ZW"
  GB4 1: "VK W"
  LU1 0: "LU"
  NL1 0: "NL W"
  NL1 1: "NL NO"
  NL1 2: "NL O"
  NL1 3: "NL NW"
  NL1 4: "NL ZW"
  NL1 5: "NL ZO"
  NO2 0: "NO"
  BE1 0 H2: "BE O H2"
  BE1 1 H2: "BE W H2"
  DE1 0 H2: "DE O H2"
  DE1 1 H2: "DE ZO H2"
  DE1 2 H2: "DE NO H2"
  DE1 3 H2: "DE ZW H2"
  DE1 4 H2: "DE NW H2"
  DK1 0 H2: "DK W H2"
  DK3 0 H2: "DK O H2"
  FR1 0 H2: "FR ZW H2"
  FR1 1 H2: "FR NW H2"
  FR1 2 H2: "FR N H2"
  FR1 3 H2: "FR NO H2"
  FR1 4 H2: "FR ZO H2"
  GB0 0 H2: "VK ZO H2"
  GB0 1 H2: "VK N H2"
  GB0 2 H2: "VK ZW H2"
  GB4 1 H2: "VK W H2"
  LU1 0 H2: "LU H2"
  NL1 0 H2: "NL W H2"
  NL1 1 H2: "NL NO H2"
  NL1 2 H2: "NL O H2"
  NL1 3 H2: "NL NW H2"
  NL1 4 H2: "NL ZW H2"
  NL1 5 H2: "NL ZO H2"
  NO2 0 H2: "NO2 0 H2"
#  tech_colors: #old tech colors
#   "onwind" : "#235ebc"
#   "onshore wind" : "#235ebc"
#   'offwind' : "#6895dd"
#   'offwind-ac' : "#6895dd"
#   'offshore wind' : "#6895dd"
#   'offshore wind ac' : "#6895dd"
#   'offwind-dc' : "#74c6f2"
#   'offshore wind dc' : "#74c6f2"
#   "hydro" : "#08ad97"
#   "hydro+PHS" : "#08ad97"
#   "PHS" : "#08ad97"
#   "hydro reservoir" : "#08ad97"
#   'hydroelectricity' : '#08ad97'
#   "ror" : "#4adbc8"
#   "run of river" : "#4adbc8"
#   'solar' : "#f9d002"
#   'solar PV' : "#f9d002"
#   'solar thermal' : '#ffef60'
#   'biomass' : '#0c6013'
#   'solid biomass' : '#06540d'
#   'biogas' : '#23932d'
#   'waste' : '#68896b'
#   'geothermal' : '#ba91b1'
#   "gas" : "#d35050"
#   "natural gas" : "#d35050"
#   "coal" : "#707070"
#   "lignite" : "#9e5a01"
#   "oil" : "#262626"
#   "H2" : "#ea048a"
#   "hydrogen storage" : "#ea048a"
#   "battery" : "#b8ea04"
#   "Electric load" : "#f9d002"
#   "electricity" : "#f9d002"
#   "lines" : "#70af1d"
#   "transmission lines" : "#70af1d"
#   "AC-AC" : "#70af1d"
#   "AC line" : "#70af1d"
#   "links" : "#8a1caf"
#   "HVDC links" : "#8a1caf"
#   "DC-DC" : "#8a1caf"
#   "DC link" : "#8a1caf"
#   "nuclear_nextgen" : "#ff9000"
#   "OCGT-nextgen" : "#d35050"
#   "CCGT-nextgen" : "#b20101"
#   "nuclear" : "#ffbc66"
#   "OCGT" : "#e59696"
#   "CCGT" : "#fe3a3a"
#   "BECCS" : "#425744"
#   "DAC" : "#85a388"
